include("${CGET_CORE_DIR}.cget/core.cmake" REQUIRED)

CGET_HAS_DEPENDENCY(CURL SUBMODULE curl.cget)
CGET_HAS_DEPENDENCY(mongoose SUBMODULE mongoose.cget)
CGET_HAS_DEPENDENCY(gflags   SUBMODULE gflags NOSUBMODULES)
CGET_HAS_DEPENDENCY(cget-cli SUBMODULE cget-cli NO_FIND_PACKAGE)

